In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.5'

In [24]:
def onehotcylinder(cylinders):
  if cylinders == 3:
    cyl = np.array([1,0,0,0,0])
  elif cylinders == 4:
    cyl = np.array([0,1,0,0,0])
  elif cylinders == 5:
    cyl = np.array([0,0,1,0,0])
  elif cylinders == 6:
    cyl = np.array([0,0,0,1,0])
  else:
    cyl = np.array([0,0,0,0,1])
  return cyl

In [23]:
onehotcylinder(4), onehotcylinder(8)

(array([0, 1, 0, 0, 0]), array([0, 0, 0, 0, 1]))

In [25]:
displacement = 307.0
horsepower = 130.0
weight = 3504.0
accel  = 12.0
cylinders = 8
origin = 1

## if cylinders = 8, origin = 1 --> onehot encoding

x_con = np.array([displacement, horsepower, weight, accel])
# cyl = np.array([0,0,0,0,1]) # 8
cyl = onehotcylinder(cylinders)
org = np.array([1,0,0]) # 1

In [ ]:
type(x_con), type(cyl), type(org)

In [9]:
# np.concatenate((a,b), axis=None)
np.round(np.concatenate((x_con, cyl, org), axis=None))

array([3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00])

[307.0, 130.0, 3504.0, 12.0, 0,0,0,0,1, 1,0,0] 표현

In [10]:
result = np.round(np.concatenate((x_con, cyl, org), axis=None))
result.shape, result

((12,),
 array([3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]))

In [14]:
# result.reshape(1,12) 
result = result.reshape(-1, result.size)
result.shape, result.size, result

((1, 12),
 12,
 array([[3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]]))

## function 이해

In [15]:
def dut(f01,s02):
  first = f01
  second = s02
  result = first + second
  return result

In [16]:
dut(4,5)

9

In [17]:
def gob(x,y,z):
  x = x
  y = y
  z = z
  result = x * y * z
  return result

In [18]:
gob(3,6,10)

180

In [20]:
# def differenceVars(*var01, **args02)
def diffparam(*var_list, **var_dict):
  print(var_dict)
  result01 = len(var_list)
  return result01

In [21]:
diffparam(1,2,3, a=2, b=4)

{'a': 2, 'b': 4}


3